# -*- coding: utf-8 -*-
"""CSST-101-MANGULABNAN-EXER1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ksE69DDxH6OLKqeR7d3BO7tVURU1j3ON
"""

is_hungry = True

def will_eat(is_hugnry):
  return is_hungry

def not_hungry(has_eaten):
  return not has_eaten

def hunger_status(is_hungry):
  if is_hungry:
    has_eaten = will_eat(is_hungry)
    is_hungry = not_hungry(has_eaten)
  return is_hungry

print(f"Status: John is {'hungry' if is_hungry else 'not hungry'}")

is_hungry = hunger_status(is_hungry)

print(f"After eating: John is {'hungry' if is_hungry else 'not hungry'}")