# -*- coding: utf-8 -*-
"""CSST-101-MANGULABNAN-EXER1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ksE69DDxH6OLKqeR7d3BO7tVURU1j3ON
"""

def is_a_human(x):
  human = {"socrates"}
  return x in human

def is_mortal(x):
  return is_a_human(x)

socrates = "socrates"
socrates_is_mortal = is_mortal(socrates)

print(f"Is {socrates} moratl? {'Yes' if socrates_is_mortal else 'No'}")