# -*- coding: utf-8 -*-
"""CSST-101-MANGULABNAN-EXER1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ksE69DDxH6OLKqeR7d3BO7tVURU1j3ON
"""

def modus(rules, facts):
  conclusions = set()

  for rules in rules:
    premise, conclusion = rules

    if premise in facts:
      conclusions.add(conclusion)

  return conclusions

rules = [("x is true", "y is true"), ("a is true", "b is false"), ("c is true", "d is true")]
facts = {"x is true", "a is true", "c is true"}
conclusions = modus(rules, facts)

print("The conclusion derived from modus ponens:")
for conclusion in conclusions:
  print(conclusion)