# -*- coding: utf-8 -*-
"""CSST-101-MANGULABNAN-EXER1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ksE69DDxH6OLKqeR7d3BO7tVURU1j3ON
"""

its_raining = True
the_ground_is_wet = its_raining
match_will_light = not the_ground_is_wet

print(f"Is it raining? {'Yes' if its_raining else 'No'}")
print(f"Is the ground wet? {'Yes' if the_ground_is_wet else 'No'}")
print(f"Will the match light? {'Yes' if match_will_light else 'No'}")